lib/discourse_chat/provider/slack/slack_command_controller.rb

render:nothing was producing an error 500 for some reason. I think this was introduced in the rails 5 update.

Replace `render nothing: true` with JSON Response

---

lib/discourse_chat/provider/matrix/matrix_provider.rb

I recently configured the Matrix provider included in `discourse-chat-integration` on a Discourse forum I help manage and I was wondering why the "chat integration matrix excerpt length" setting didn't seem to have any effect on the excerpt length of the messages posted by the bot.
I just looked at the code of this plugin and I found a typo that explains why I was having this issue 🙂

use SiteSetting.chat_integration_matrix_excerpt_length for the Matrix provider

---

.travis.yml
lib/discourse_chat/provider/slack/slack_command_controller.rb
lib/discourse_chat/provider/slack/slack_transcript.rb
spec/lib/discourse_chat/provider/slack/slack_command_controller_spec.rb
spec/lib/discourse_chat/provider/slack/slack_transcript_spec.rb

Adds support and tests for slash commands in private areas of slack including 'private channels' (aka groups), and 'direct messages' (aka IMs). 
Also adds basic transcript support for threads.

Slash command and transcript improvements

---

lib/discourse_chat/provider/slack/slack_transcript.rb
spec/lib/discourse_chat/provider/slack/slack_command_controller_spec.rb
spec/lib/discourse_chat/provider/slack/slack_transcript_spec.rb

While it's not explicitly described in [API description for users.list method](https://api.slack.com/methods/users.list) Slack returns users.list limited to 1000 members. So if we want to load longer list, we need to use [pagination](https://api.slack.com/docs/pagination)

fix loading user.list longer than 1000

---

config/locales/server.en.yml
config/settings.yml
lib/discourse_chat/provider/matrix/matrix_provider.rb

Notices are problematic on certain IRC clients and lead to bans if the Matrix channel is bridged to IRC.
Fixes [Change communication with Matrix from notice to message](https://meta.discourse.org/t/change-communication-with-matrix-from-notice-to-message/93874).

Add Matrix option for using plain text instead of notice

---

lib/discourse_chat/provider/slack/slack_message.rb
lib/discourse_chat/provider/slack/slack_transcript.rb
spec/lib/discourse_chat/provider/slack/slack_command_controller_spec.rb
spec/lib/discourse_chat/provider/slack/slack_transcript_spec.rb

The "name" field from the Slack API is the left-hand side of the email address in many cases.  This information is not otherwise available so we shouldn't expose it in forum posts.
This will also make the transcripts more consistent with the way Slack displays usernames.
I think the automated tests will need an update, once I hear that someone is looking at PRs here I will try.

Use Slack display names instead of the "name" field

---

lib/discourse_chat/provider/telegram/telegram_initializer.rb

Hello,
This PR fixes the error:  `undefined local variable or method 'site_setting_saved' for main:Object (NameError)` for Discourse `v2.2.4`.
Thanks!

FIX: undefined local variable or method 'site_setting_saved'

---

app/controllers/chat_controller.rb

I think that passing attributes to save method is not necessary when the Object was initialized with them.
Problem is that with Rails 6.0.0 (https://github.com/discourse/discourse/pull/8083) this code is not working https://travis-ci.org/discourse/discourse/jobs/582556988

FIX: Save on chat_controller ready for Rails 6.0.0

---

config/locales/server.en.yml
config/settings.yml
lib/discourse_chat/provider/slack/slack_provider.rb

Adds support for custom bot's username by adding the `chat_integration_slack_username` setting to `settings.yml`. It broadens the possibilities for that _username_ since it was previously set to the site's title, and it wasn't customizable.
You can now get something like this:

FEATURE: support for slack custom username

---

app/jobs/onceoff/add_type_field.rb
app/jobs/onceoff/migrate_from_slack_official.rb
app/jobs/regular/notify_chats.rb

Zeitwerk is failing when we are searching for Jobs::Onceoff and Jobs::Base without going back to the top-level namespace (this is correlated to the fact that we got Onceoff base class and module with the same name). 
I noticed that in plugins we are using sometimes :: and sometimes not and that gives me comfort that this change will not break anything.
Travis error: https://travis-ci.org/discourse/discourse/jobs/585072364

[WIP] FIX: Use top-level namespace for base classes

---

lib/discourse_chat/provider/telegram/telegram_command_controller.rb

The `text` field is marked optional, and is not guaranteed to exist:
https://core.telegram.org/bots/api#message
We should silently ignore these actions (while responding with a
positive acknowledgement) instead of throwing a `NoMethodError`.

FIX: telegram: Not all channel posts contain text

---

lib/discourse_chat/provider/telegram/telegram_initializer.rb
spec/lib/discourse_chat/provider/telegram/telegram_command_controller_spec.rb
spec/lib/discourse_chat/provider/telegram/telegram_provider_spec.rb

The `site_setting_changed` event passes the setting name as a symbol, not a string. This commit also removes the backwards-compatible `site_setting_saved` event, which was deprecated in 2.3.0.

FIX: Update telegram webhook correctly and remove old code

---

assets/javascripts/admin/templates/modal/admin-plugins-chat-edit-channel.hbs
assets/javascripts/admin/templates/modal/admin-plugins-chat-edit-rule.hbs
assets/stylesheets/chat-integration-admin.scss

These had been broken at some point by core changes:
Before:
After:

UX: Style fixes for rule/channel modals

---

config/locales/server.en.yml
lib/discourse_chat/provider/slack/slack_command_controller.rb
spec/lib/discourse_chat/provider/slack/slack_command_controller_spec.rb

- Stop using `break` in a block - it doesn't work
- Return specific error messages for user / message-history / message errors
- Tidy up the SlackCommandController to make all non-requestable methods private
- Add a test to ensure error messages are passed correctly to Slack

FIX: Improve error handling for slack transcript generation

---

lib/discourse_chat/provider/slack/slack_message.rb
spec/lib/discourse_chat/provider/slack/slack_transcript_spec.rb

- Fix multi-line code blocks
- Add strikethrough support
- Fix HTML entities inside code blocks
- Do not process formatting inside code blocks
- Ensure links are never created with no URL
- Replace - with _ in emoji names

FEATURE: Improve formatting for Slack transcript messages

---

config/locales/server.en.yml
lib/discourse_chat/provider/slack/slack_command_controller.rb
lib/discourse_chat/provider/slack/slack_provider.rb
lib/discourse_chat/provider/slack/slack_transcript.rb
spec/lib/discourse_chat/provider/slack/slack_command_controller_spec.rb

Once configured, this adds a new item to the context menu of slack messages. When clicked, the menu item will generate a transcript and present the user with a custom "Post to Discourse" modal. This provides the same functionality as the existing slash-command interface, but is much more user friendly.

FEATURE: Add support for slack message shortcuts for transcripts

---

config/locales/server.en.yml

https://meta.discourse.org/t/chat-integration-error-links-to-the-wrong-url/204977

FIX: Update dashboard warning link to point to new chat-integration URL

---

assets/javascripts/admin/controllers/modals/admin-plugins-chat-integration-edit-channel.js.es6

This was deprecated in https://github.com/discourse/discourse/commit/e39d89ecd9119f69f464d92a16d59d77cc746081, and stopped working following the move to Ember CLI

FIX: Remove use of InputValidation library

---

lib/discourse_chat_integration/provider/telegram/telegram_command_controller.rb

This was sourced from #84, with suggestions applied.
- Fixed problem with inappropriate bot responses to non-command messages.
- tweaked return of process_command

Fixed telegram bot answering to improper commands (supersedes #84)

---

assets/javascripts/admin/controllers/modals/admin-plugins-chat-integration-edit-channel.js.es6

(Ember's `defineProperty` no longer sees to fire the notifyPropertyChange event, so we need to do it manually)

FIX: Ensure edit modal validation works on first opening

---

db/migrate/20211202120030_add_unique_index_to_slack_thread_ts.rb
lib/discourse_chat_integration/provider/slack/slack_provider.rb
spec/lib/discourse_chat_integration/provider/slack/slack_provider_spec.rb

When notifications about a topic are posted to multiple slack channels, and the Discourse channels are configured to "thread" the notifications, each channel will have a different thread_id. Previously we were only storing a single slack thread id per Discourse topic. This commit fixes that logic, so that threads in different channels are tracked separately.

FIX: Store slack thread_ts on a per-channel basis

---

db/post_migrate/20220215103720_update_discord_webhook_domains.rb
lib/discourse_chat_integration/provider/discord/discord_provider.rb
spec/lib/discourse_chat_integration/provider/discord/discord_provider_spec.rb

discordapp.com is being deprecated and replaced with discord.com - https://github.com/discord/discord-api-docs/discussions/4510

DEV: Update Discord webhook domain

---

config/locales/client.en.yml
config/locales/server.en.yml
lib/discourse_chat_integration/provider/slack/slack_provider.rb
plugin.rb

This allows for the discourse automation plugin to have a "Send Slack
Message" script.
The script fields are a message, url, and slack channel. This will allow
for a custom slack message to be posted but can link back to an
arbitrary url (hopefully a discourse url) like a list of unanswered
topics instead of strictly only allowing a slack message that links back
to a Discourse Post object.

DEV: Adds post_to_slack scriptable for automation

---

assets/javascripts/admin/templates/modal/admin-plugins-chat-integration-edit-rule.hbs

The select-kit API has changed since this plugin's original implementation. `rootNoneLabel` and `rootNone` have been replaced with `none`

FIX: Use correct copy for 'all categories'

---

lib/discourse_chat_integration/provider/slack/slack_transcript.rb
spec/lib/discourse_chat_integration/provider/slack/slack_transcript_spec.rb

This should help to avoid Slack API rate limiting in very large slack communities

PERF: Cache slack users list for 10 minutes

---

lib/discourse_chat_integration/provider/slack/slack_transcript.rb
spec/lib/discourse_chat_integration/provider/slack/slack_transcript_spec.rb

We were using the internal UID of the channel in the hint, which would then fail to match any 'channel' configs in Discourse (which use the human-friendly `#channel` format). This was causing automatic threading for transcripts to fail.

FIX: Use correct identifier in transcript thread hint

---

plugin.rb

This would cause admin checks to fail when the plugin is disabled.
Unfortunately plugin-contributed AdminDashboardData checks are not currently testable, but I hope to fix that in a future core commit.
Follow-up to 8de3e498b2814ffd87220b4de8051577abf8c5de

FIX: Correct error in AdminDashboardData problem check

---

assets/javascripts/discourse/templates/admin/plugins-chat-integration.hbs
assets/stylesheets/chat-integration-admin.scss

We usually push the settings button to the right, the old float here isn't working
Before: 
After:

UX: admin controls alignment

---

app/helpers/helper.rb
lib/discourse_chat_integration/provider/discord/discord_provider.rb
lib/discourse_chat_integration/provider/flowdock/flowdock_provider.rb
lib/discourse_chat_integration/provider/groupme/groupme_provider.rb
lib/discourse_chat_integration/provider/matrix/matrix_provider.rb
lib/discourse_chat_integration/provider/mattermost/mattermost_provider.rb
lib/discourse_chat_integration/provider/rocketchat/rocketchat_provider.rb
lib/discourse_chat_integration/provider/slack/slack_provider.rb
lib/discourse_chat_integration/provider/teams/teams_provider.rb
lib/discourse_chat_integration/provider/telegram/telegram_provider.rb
lib/discourse_chat_integration/provider/webex/webex_provider.rb
lib/discourse_chat_integration/provider/zulip/zulip_provider.rb
spec/helpers/helper_spec.rb

This commit centralizes 'display name' generation into a helper, and updates it to respect core preferences for `enable_names` and `prioritize_username_in_ux`.
https://meta.discourse.org/t/discourse-chat-integration-shows-users-name-on-posted-discord-items/181058

FIX: Respect core settings when rendering user names/usernames

---

lib/discourse_chat_integration/provider/telegram/telegram_command_controller.rb
spec/lib/discourse_chat_integration/provider/telegram/telegram_command_controller_spec.rb

This PR concerns the Telegram integration. Currently, we always try to process commands when we receive a hook from Telegram. To do so we rely on the `text` parameters from a Telegram message but the [API documentation](https://core.telegram.org/bots/api#message) tells us this parameters is actually optional. It means sometimes it’s not present in the payload we receive but we still try to access it resulting in a crash.
This PR addresses the issue by simply returning early from the `#process_command` method when `text` is missing from the payload since we don’t have anything to process then.

FIX: Don’t process commands when 'text' is missing

---

lib/discourse_chat_integration/provider/slack/slack_provider.rb
spec/lib/discourse_chat_integration/provider/slack/slack_provider_spec.rb

Previously we were using the `ts` of the previous message we sent to the thread. While this did work under some situations, it's not recommended in the Slack API docs, and can lead to some unexpected behavior (e.g. when one of the threaded messages is deleted).
This commit updates our logic to always use Slack's returned `thread_ts`, which represents the thread's parent.

FIX: Always use parent thread_ts for slack threads

---

app/models/rule.rb
app/services/manager.rb
assets/javascripts/admin/models/rule.js
config/locales/client.en.yml
spec/services/manager_spec.rb

This relies on core PR - 
https://github.com/discourse/discourse/pull/20812
The above PR creates small action posts with tag change information. There are some important custom fields added in there, so that the chat-integration plugin can pick up previous state and new state, then decide if the post is actionable.
The new filter `Tag added` works like a charm with the existing tag filtering setup. If a tag is added to a topic with a matching rule, the rule topic's current tags will be compared with the tags in the rule to decide if the post should make it's way to chat. The post that goes to chat is the small action describing what happened, so there are no additional changes need to explain the chat message.

FEATURE: New rule filter to send message when topic tags change

---

app/services/manager.rb
spec/services/manager_spec.rb

This hooks into small action posts created by `PostRevisor`. When a post is created showing that the category for the topic has changed, we look for `follow` rules (on first post) that match _only_ the new category for the topic, and send a message through chat.

FEATURE: Trigger follow rules when category changes

---

app/services/manager.rb
spec/services/manager_spec.rb

There was a bug reported that normal posts in a tagged were sent to chat when a `tag_added` rule was present. This is because we aren't filtering out `tag_added` rules when the post _isn't_ a corresponding small_action post.
This PR filters out those rules!

FIX: stop 'tag_added' rules from firing for normal posts

---

lib/discourse_chat_integration/provider/slack/slack_provider.rb

We have replaced the `#pluck_first` freedom patch with the native `#pick` in core [here](https://github.com/discourse/discourse/pull/19893).
This change is updates this plugin in the same fashion.

DEV: Replace #pluck_first monkey patch with native #pick

---

spec/services/manager_spec.rb

We're updating core to change TL based access settings to be group based. This requires some updates of tests to work correctly. (The existing test setup gives false positives.)
Related: https://github.com/discourse/discourse/pull/24257

DEV: Update test setup to work with auto groups

---

app/services/problem_check/channel_errors.rb
lib/discourse_chat_integration/provider.rb
plugin.rb
spec/fabricators/channel_fabricator.rb
spec/services/problem_check/channel_errors_spec.rb

We're promoting problem checks to first class citizens in core. This migrates the problem check to the new API.
In the process of adding tests for this check, I discovered what seems like a mistake that likely means this check never worked until now. (See inline comment.)

DEV: Promote channel error check to ProblemCheck

---

plugin.rb

In https://github.com/discourse/discourse/pull/26413 we are changing problem checks to require explicit registration. As part of that we're adding a filtered register to the plugin registry. This PR makes use of that new register.

DEV: Explicitly register problem check

---

plugin.rb

Reverts discourse/discourse-chat-integration#191
This is causing Discourse Core CI to fail, so reverting for now.
```
64: from bin/rake:13:in `<main>'
63: from /__w/discourse/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:80:in `run'
62: from /__w/discourse/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
61: from /__w/discourse/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:83:in `block in run'
60: from /__w/discourse/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
59: from /__w/discourse/discourse/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
58: from …
```

Revert "DEV: Explicitly register problem check"

---

plugin.rb

Reverts discourse/discourse-chat-integration#192
Reimplement https://github.com/discourse/discourse-chat-integration/pull/191 as the Discourse Core CI issue was unrelated.

Revert "Revert "DEV: Explicitly register problem check""

---

spec/helpers/helper_spec.rb

I am enabling `config.i18n.raise_on_missing_translations` in core. That revealed that one of the tests here where we use a dummy provider is rendering "Translation missing ..."
This change copies the translations from the Slack provider to the dummy provider in the test so we're testing real values.

FIX: Add missing dummy translations for tests

---

config/locales/client.en.yml
config/locales/server.en.yml

The GroupMe provider is looking for a translated error message in the server-side locale file, but the translation has been placed in the client-side file. This fixes that.
**Before:**
```
Randomized with seed 49471
FF
Failures:
1) DiscourseChatIntegration::Provider::GroupmeProvider.trigger_notifications sends a request
Failure/Error: raise I18n::MissingTranslationData.new(locale, key)
I18n::MissingTranslationData:
Translation missing: en.chat_integration.provider.groupme.errors.instance_names_issue
2) DiscourseChatIntegration::Provider::GroupmeProvider.trigger_notifications handles errors correctly
Failure/Error:
expect { described_class.trigger_notification(post, chan1, nil) }.to raise_exception(
::DiscourseChatIntegration::ProviderError,
)
expected …
```

FIX: Move GroupMe error message to server side translations

---

app/services/problem_check/channel_errors.rb
config/locales/server.en.yml

[Meta](https://meta.discourse.org/t/translation-missing-en-gb-dashboard-problem-channel-errors/311104)
As part of enhancing problem checks and admin notices, we standardized the location of the problem check messages' locale keys. However, we overlooked this one in the plugin, resulting in a missing translation on the dashboard.
This PR puts the locale key in the place expected by the admin notice system. (Next there will be a PR in core to make this more robust/easy to catch/configurable.)

FIX: Move chat integration problem check message to correct locale key

---

admin/assets/javascripts/admin/models/rule.js
admin/assets/javascripts/admin/routes/admin-plugins-chat-integration-provider.js
app/services/manager.rb
config/locales/client.en.yml
spec/services/manager_spec.rb

Reverts discourse/discourse-chat-integration#214

FEATURE: re-revert chat-integration move to discourse-automation

---

lib/discourse_chat_integration/chat_integration_reference_post.rb
plugin.rb
spec/lib/discourse_chat_integration/chat_integration_reference_post_spec.rb

Before it automation would fail because the topic does not have `full_url` method

FIX: adjust `full_url` method in `ChatIntegrationReferencePost` to return the correct URL

---

plugin.rb
spec/integration/automation_spec.rb

before topic tags changes trigger would fire on topic creation, now it only fires on tags changes

FIX: Message triggering on topic creation

---

admin/assets/javascripts/admin/components/modal/channel-error.hbs
spec/system/create_channel_spec.rb

Before, there was an issue where the error modal was not showing the data. This was because the error modal was not being shown when there were errors.
before: 
https://github.com/user-attachments/assets/0886277a-2aea-4655-8efa-63736bd35899
now:  
https://github.com/user-attachments/assets/62334db9-f742-4189-881b-781720c92438

FIX: Error modal not showing data

---

spec/system/create_channel_spec.rb

the error:
```
Randomized with seed 43756
.F
Failures:
1) Create channel shows error in chanel modal
Failure/Error: super
Capybara::ElementNotFound:
Unable to find css ".error-message"
[Screenshot Image]: /var/www/discourse/tmp/capybara/failures_r_spec_example_groups_create_channel_shows_error_in_chanel_modal_523.png
~~~~~~~ JS LOGS ~~~~~~~
(no logs)
```
To try solving this, I've changed the ordering, before visiting the page I already set up the channel error.

FIX: Update flaky test in showing error modal

---

admin/assets/javascripts/admin/components/channel-details.hbs
admin/assets/javascripts/admin/components/rule-row.hbs
admin/assets/javascripts/admin/templates/plugins-chat-integration.hbs

This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: Update more deprecated Font Awesome icon names

---

admin/assets/javascripts/admin/models/rule.js

This PR updates the deprecated `exclamation-circle` and `times-circle` icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: update deprecated icon names exclamation-circle and times-circle

---

app/services/manager.rb
spec/services/manager_spec.rb

We [moved](https://github.com/discourse/discourse/pull/29602/files) `category_changed` notification to be a `whisper` but we forgot to update the check in `manager.rb` to verify not for a `small_post` but for a whisper.
Added a test to cover this case.

FIX: Topic changing category was not triggering notifications

---

lib/discourse_chat_integration/provider/discord/discord_provider.rb
spec/lib/discourse_chat_integration/provider/discord/discord_provider_spec.rb

Discourse is able to share topics and replies to normal Discord channels, but it doesn't work with forum channels, which require an additional `thread_name` parameter.
This change fixes the issue by checking for the specific error the Discord returns when trying to share to a forum channel, adding the `thread_name`, then trying again.
This is intentionally a minimal fix, additional work would be required to make the sharing more closely fit the style of Discord forum channels.
Setup sharing to Discord, and ensure that posts are shared as expected to different channel types.

FIX: Sharing to Discord forum channels requires a thread_name
